# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'serial_helper.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(811, 584)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../run/media/guwenjun/F2C0D433C0D3FFB1/Users/Jack/Desktop/Blog/source/images/linux/linux1.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sendbox = QtWidgets.QGroupBox(self.centralwidget)
        self.sendbox.setGeometry(QtCore.QRect(280, 300, 511, 241))
        self.sendbox.setObjectName("sendbox")
        self.checkBox = QtWidgets.QCheckBox(self.sendbox)
        self.checkBox.setGeometry(QtCore.QRect(10, 200, 101, 22))
        self.checkBox.setObjectName("checkBox")
        self.clear_send_button = QtWidgets.QPushButton(self.sendbox)
        self.clear_send_button.setGeometry(QtCore.QRect(170, 200, 88, 31))
        self.clear_send_button.setObjectName("clear_send_button")
        self.send_button = QtWidgets.QPushButton(self.sendbox)
        self.send_button.setGeometry(QtCore.QRect(290, 200, 88, 31))
        self.send_button.setObjectName("send_button")
        self.sendcontent = QtWidgets.QTextEdit(self.sendbox)
        self.sendcontent.setGeometry(QtCore.QRect(10, 30, 491, 161))
        self.sendcontent.setObjectName("sendcontent")
        self.auto_send_button = QtWidgets.QPushButton(self.sendbox)
        self.auto_send_button.setGeometry(QtCore.QRect(400, 200, 81, 31))
        self.auto_send_button.setObjectName("auto_send_button")
        self.receivebox = QtWidgets.QGroupBox(self.centralwidget)
        self.receivebox.setGeometry(QtCore.QRect(280, 50, 511, 241))
        self.receivebox.setObjectName("receivebox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.receivebox)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 200, 101, 22))
        self.checkBox_2.setObjectName("checkBox_2")
        self.clear_receive_button = QtWidgets.QPushButton(self.receivebox)
        self.clear_receive_button.setGeometry(QtCore.QRect(170, 200, 88, 31))
        self.clear_receive_button.setObjectName("clear_receive_button")
        self.receivecontent = QtWidgets.QTextBrowser(self.receivebox)
        self.receivecontent.setGeometry(QtCore.QRect(10, 30, 491, 161))
        self.receivecontent.setObjectName("receivecontent")
        self.serial_set = QtWidgets.QGroupBox(self.centralwidget)
        self.serial_set.setGeometry(QtCore.QRect(10, 50, 241, 241))
        self.serial_set.setObjectName("serial_set")
        self.label = QtWidgets.QLabel(self.serial_set)
        self.label.setGeometry(QtCore.QRect(30, 30, 61, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.serial_set)
        self.label_2.setGeometry(QtCore.QRect(40, 60, 51, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.serial_set)
        self.label_3.setGeometry(QtCore.QRect(40, 120, 51, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.serial_set)
        self.label_4.setGeometry(QtCore.QRect(40, 90, 51, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.serial_set)
        self.label_5.setGeometry(QtCore.QRect(40, 150, 51, 31))
        self.label_5.setObjectName("label_5")
        self.open_serial_button = QtWidgets.QPushButton(self.serial_set)
        self.open_serial_button.setGeometry(QtCore.QRect(80, 193, 88, 31))
        self.open_serial_button.setObjectName("open_serial_button")
        self.serial_choose = QtWidgets.QComboBox(self.serial_set)
        self.serial_choose.setEnabled(True)
        self.serial_choose.setGeometry(QtCore.QRect(100, 30, 83, 31))
        self.serial_choose.setEditable(True)
        self.serial_choose.setObjectName("serial_choose")
        self.serial_choose.addItem("")
        self.serial_choose.addItem("")
        self.serial_choose.addItem("")
        self.serial_choose.addItem("")
        self.baudrate = QtWidgets.QComboBox(self.serial_set)
        self.baudrate.setEnabled(True)
        self.baudrate.setGeometry(QtCore.QRect(100, 60, 83, 31))
        self.baudrate.setEditable(True)
        self.baudrate.setObjectName("baudrate")
        self.baudrate.addItem("")
        self.baudrate.addItem("")
        self.datasize = QtWidgets.QComboBox(self.serial_set)
        self.datasize.setEnabled(True)
        self.datasize.setGeometry(QtCore.QRect(100, 90, 83, 31))
        self.datasize.setEditable(True)
        self.datasize.setObjectName("datasize")
        self.datasize.addItem("")
        self.datasize.addItem("")
        self.datasize.addItem("")
        self.checkbyte = QtWidgets.QComboBox(self.serial_set)
        self.checkbyte.setEnabled(True)
        self.checkbyte.setGeometry(QtCore.QRect(100, 120, 83, 31))
        self.checkbyte.setEditable(True)
        self.checkbyte.setObjectName("checkbyte")
        self.checkbyte.addItem("")
        self.stopbyte = QtWidgets.QComboBox(self.serial_set)
        self.stopbyte.setEnabled(True)
        self.stopbyte.setGeometry(QtCore.QRect(100, 150, 83, 31))
        self.stopbyte.setEditable(True)
        self.stopbyte.setObjectName("stopbyte")
        self.stopbyte.addItem("")
        self.commu_status = QtWidgets.QGroupBox(self.centralwidget)
        self.commu_status.setGeometry(QtCore.QRect(10, 300, 241, 241))
        self.commu_status.setObjectName("commu_status")
        self.label_6 = QtWidgets.QLabel(self.commu_status)
        self.label_6.setGeometry(QtCore.QRect(30, 40, 61, 31))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.commu_status)
        self.label_7.setGeometry(QtCore.QRect(30, 80, 61, 31))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.commu_status)
        self.label_8.setGeometry(QtCore.QRect(30, 120, 61, 31))
        self.label_8.setObjectName("label_8")
        self.serial_defined = QtWidgets.QTextBrowser(self.commu_status)
        self.serial_defined.setGeometry(QtCore.QRect(100, 40, 71, 31))
        self.serial_defined.setObjectName("serial_defined")
        self.sendbytecount = QtWidgets.QTextBrowser(self.commu_status)
        self.sendbytecount.setGeometry(QtCore.QRect(100, 80, 71, 31))
        self.sendbytecount.setTabChangesFocus(False)
        self.sendbytecount.setObjectName("sendbytecount")
        self.receivebytecount = QtWidgets.QTextBrowser(self.commu_status)
        self.receivebytecount.setGeometry(QtCore.QRect(100, 120, 71, 31))
        self.receivebytecount.setObjectName("receivebytecount")
        self.clear_count_button = QtWidgets.QPushButton(self.commu_status)
        self.clear_count_button.setGeometry(QtCore.QRect(80, 190, 88, 34))
        self.clear_count_button.setObjectName("clear_count_button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Serial"))
        self.sendbox.setToolTip(_translate("MainWindow", "<html><head/><body><p>接收</p></body></html>"))
        self.sendbox.setTitle(_translate("MainWindow", "发送框"))
        self.checkBox.setText(_translate("MainWindow", "16进制显示"))
        self.clear_send_button.setText(_translate("MainWindow", "清空发送框"))
        self.send_button.setText(_translate("MainWindow", "手工发送"))
        self.auto_send_button.setText(_translate("MainWindow", "自动发送"))
        self.receivebox.setTitle(_translate("MainWindow", "接收框"))
        self.checkBox_2.setText(_translate("MainWindow", "16进制显示"))
        self.clear_receive_button.setText(_translate("MainWindow", "清空接收框"))
        self.serial_set.setTitle(_translate("MainWindow", "串口设置"))
        self.label.setText(_translate("MainWindow", "选择串口："))
        self.label_2.setText(_translate("MainWindow", "波特率："))
        self.label_3.setText(_translate("MainWindow", "校验位："))
        self.label_4.setText(_translate("MainWindow", "数据位："))
        self.label_5.setText(_translate("MainWindow", "停止位："))
        self.open_serial_button.setText(_translate("MainWindow", "打开串口"))
        self.serial_choose.setItemText(0, _translate("MainWindow", "COM1"))
        self.serial_choose.setItemText(1, _translate("MainWindow", "COM2"))
        self.serial_choose.setItemText(2, _translate("MainWindow", "COM3"))
        self.serial_choose.setItemText(3, _translate("MainWindow", "COM4"))
        self.baudrate.setItemText(0, _translate("MainWindow", "9600"))
        self.baudrate.setItemText(1, _translate("MainWindow", "4800"))
        self.datasize.setItemText(0, _translate("MainWindow", "8"))
        self.datasize.setItemText(1, _translate("MainWindow", "4"))
        self.datasize.setItemText(2, _translate("MainWindow", "16"))
        self.checkbyte.setItemText(0, _translate("MainWindow", "None"))
        self.stopbyte.setItemText(0, _translate("MainWindow", "1"))
        self.commu_status.setTitle(_translate("MainWindow", "通讯状态"))
        self.label_6.setText(_translate("MainWindow", "选择串口："))
        self.label_7.setText(_translate("MainWindow", "发送字节："))
        self.label_8.setText(_translate("MainWindow", "接收字节："))
        self.serial_defined.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.sendbytecount.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.receivebytecount.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.clear_count_button.setText(_translate("MainWindow", "清除计数"))

